#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

if [ -z "$TRAVIS_TAG" ]
then
      DOCKER_VERSION="latest"
else
      DOCKER_VERSION=$TRAVIS_TAG
fi

echo "docker tag and push $1 for version $DOCKER_VERSION"
docker image tag "$1":latest "$1":"$DOCKER_VERSION"
docker push "$1":"$DOCKER_VERSION"
echo "push done"
