name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  REPO: minipaint
  DOCKERHUB_USER: pfav

jobs:
  build_and_push:
    name: Build and Push Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: REVISION=${{ github.ref == 'refs/heads/main' && 'main' || github.ref_name }}
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.REPO }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
